ny_tax_rates = [
    {"location": "New York State only", "rate": 4.0, "code": "0021", "is_city": False, "clean_name": "New York State"},
    {"location": "Albany", "rate": 8.0, "code": "0181", "is_city": False, "clean_name": "Albany"},
    {"location": "Allegany", "rate": 8.5, "code": "0221", "is_city": False, "clean_name": "Allegany"},
    {"location": "Broome", "rate": 8.0, "code": "0321", "is_city": False, "clean_name": "Broome"},
    {"location": "Cattaraugus - except", "rate": 8.0, "code": "0481", "is_city": False, "clean_name": "Cattaraugus"},
    {"location": "Olean (city)", "rate": 8.0, "code": "0441", "is_city": True, "clean_name": "Olean"},
    {"location": "Salamanca (city)", "rate": 8.0, "code": "0431", "is_city": True, "clean_name": "Salamanca"},
    {"location": "Cayuga - except", "rate": 8.0, "code": "0511", "is_city": False, "clean_name": "Cayuga"},
    {"location": "Auburn (city)", "rate": 8.0, "code": "0561", "is_city": True, "clean_name": "Auburn"},
    {"location": "Chautauqua", "rate": 8.0, "code": "0651", "is_city": False, "clean_name": "Chautauqua"},
    {"location": "Chemung", "rate": 8.0, "code": "0711", "is_city": False, "clean_name": "Chemung"},
    {"location": "Chenango - except", "rate": 8.0, "code": "0861", "is_city": False, "clean_name": "Chenango"},
    {"location": "Norwich (city)", "rate": 8.0, "code": "0831", "is_city": True, "clean_name": "Norwich"},
    {"location": "Clinton", "rate": 8.0, "code": "0921", "is_city": False, "clean_name": "Clinton"},
    {"location": "Columbia", "rate": 8.0, "code": "1021", "is_city": False, "clean_name": "Columbia"},
    {"location": "Cortland", "rate": 8.0, "code": "1131", "is_city": False, "clean_name": "Cortland"},
    {"location": "Delaware", "rate": 8.0, "code": "1221", "is_city": False, "clean_name": "Delaware"},
    {"location": "Dutchess", "rate": 8.125, "code": "1311", "is_city": False, "clean_name": "Dutchess"},
    {"location": "Erie", "rate": 8.75, "code": "1451", "is_city": False, "clean_name": "Erie"},
    {"location": "Essex", "rate": 8.0, "code": "1521", "is_city": False, "clean_name": "Essex"},
    {"location": "Franklin", "rate": 8.0, "code": "1621", "is_city": False, "clean_name": "Franklin"},
    {"location": "Fulton - except", "rate": 8.0, "code": "1791", "is_city": False, "clean_name": "Fulton"},
    {"location": "Gloversville (city)", "rate": 8.0, "code": "1741", "is_city": True, "clean_name": "Gloversville"},
    {"location": "Johnstown (city)", "rate": 8.0, "code": "1751", "is_city": True, "clean_name": "Johnstown"},
    {"location": "Genesee", "rate": 8.0, "code": "1811", "is_city": False, "clean_name": "Genesee"},
    {"location": "Greene", "rate": 8.0, "code": "1911", "is_city": False, "clean_name": "Greene"},
    {"location": "Hamilton", "rate": 8.0, "code": "2011", "is_city": False, "clean_name": "Hamilton"},
    {"location": "Herkimer", "rate": 8.25, "code": "2121", "is_city": False, "clean_name": "Herkimer"},
    {"location": "Jefferson", "rate": 8.0, "code": "2221", "is_city": False, "clean_name": "Jefferson"},
    {"location": "Lewis", "rate": 8.0, "code": "2321", "is_city": False, "clean_name": "Lewis"},
    {"location": "Livingston", "rate": 8.0, "code": "2411", "is_city": False, "clean_name": "Livingston"},
    {"location": "Madison - except", "rate": 8.0, "code": "2511", "is_city": False, "clean_name": "Madison"},
    {"location": "Oneida (city)", "rate": 8.0, "code": "2541", "is_city": True, "clean_name": "Oneida"},
    {"location": "Monroe", "rate": 8.0, "code": "2611", "is_city": False, "clean_name": "Monroe"},
    {"location": "Montgomery", "rate": 8.0, "code": "2781", "is_city": False, "clean_name": "Montgomery"},
    {"location": "Nassau", "rate": 8.625, "code": "2811", "is_city": False, "clean_name": "Nassau"},
    {"location": "New York City", "rate": 8.875, "code": "8081", "is_city": True, "clean_name": "New York City"},
    {"location": "Niagara", "rate": 8.0, "code": "2911", "is_city": False, "clean_name": "Niagara"},
    {"location": "Oneida - except", "rate": 8.75, "code": "3010", "is_city": False, "clean_name": "Oneida"},
    {"location": "Rome (city)", "rate": 8.75, "code": "3015", "is_city": True, "clean_name": "Rome"},
    {"location": "Utica (city)", "rate": 8.75, "code": "3018", "is_city": True, "clean_name": "Utica"},
    {"location": "Onondaga", "rate": 8.0, "code": "3121", "is_city": False, "clean_name": "Onondaga"},
    {"location": "Ontario", "rate": 7.5, "code": "3211", "is_city": False, "clean_name": "Ontario"},
    {"location": "Orange", "rate": 8.125, "code": "3321", "is_city": False, "clean_name": "Orange"},
    {"location": "Orleans", "rate": 8.0, "code": "3481", "is_city": False, "clean_name": "Orleans"},
    {"location": "Oswego - except", "rate": 8.0, "code": "3501", "is_city": False, "clean_name": "Oswego"},
    {"location": "Oswego (city)", "rate": 8.0, "code": "3561", "is_city": True, "clean_name": "Oswego"},
    {"location": "Otsego", "rate": 8.0, "code": "3621", "is_city": False, "clean_name": "Otsego"},
    {"location": "Putnam", "rate": 8.375, "code": "3731", "is_city": False, "clean_name": "Putnam"},
    {"location": "Rensselaer", "rate": 8.0, "code": "3881", "is_city": False, "clean_name": "Rensselaer"},
    {"location": "Rockland", "rate": 8.375, "code": "3921", "is_city": False, "clean_name": "Rockland"},
    {"location": "St. Lawrence - except", "rate": 8.0, "code": "4091", "is_city": False, "clean_name": "St. Lawrence"},
    {"location": "Ogdensburg (city)", "rate": 8.0, "code": "4012", "is_city": True, "clean_name": "Ogdensburg"},
    {"location": "Saratoga - except", "rate": 7.0, "code": "4111", "is_city": False, "clean_name": "Saratoga"},
    {"location": "Saratoga Springs (city)", "rate": 7.0, "code": "4131", "is_city": True, "clean_name": "Saratoga Springs"},
    {"location": "Schenectady", "rate": 8.0, "code": "4241", "is_city": False, "clean_name": "Schenectady"},
    {"location": "Schoharie", "rate": 8.0, "code": "4321", "is_city": False, "clean_name": "Schoharie"},
    {"location": "Schuyler", "rate": 8.0, "code": "4411", "is_city": False, "clean_name": "Schuyler"},
    {"location": "Seneca", "rate": 8.0, "code": "4511", "is_city": False, "clean_name": "Seneca"},
    {"location": "Steuben", "rate": 8.0, "code": "4691", "is_city": False, "clean_name": "Steuben"},
    {"location": "Suffolk", "rate": 8.25, "code": "4711", "is_city": False, "clean_name": "Suffolk"},
    {"location": "Sullivan", "rate": 8.0, "code": "4821", "is_city": False, "clean_name": "Sullivan"},
    {"location": "Tioga", "rate": 8.0, "code": "4921", "is_city": False, "clean_name": "Tioga"},
    {"location": "Tompkins - except", "rate": 8.0, "code": "5081", "is_city": False, "clean_name": "Tompkins"},
    {"location": "Ithaca (city)", "rate": 8.0, "code": "5021", "is_city": True, "clean_name": "Ithaca"},
    {"location": "Ulster", "rate": 8.0, "code": "5111", "is_city": False, "clean_name": "Ulster"},
    {"location": "Warren - except", "rate": 7.0, "code": "5281", "is_city": False, "clean_name": "Warren"},
    {"location": "Glens Falls (city)", "rate": 7.0, "code": "5211", "is_city": True, "clean_name": "Glens Falls"},
    {"location": "Washington", "rate": 7.0, "code": "5311", "is_city": False, "clean_name": "Washington"},
    {"location": "Wayne", "rate": 8.0, "code": "5421", "is_city": False, "clean_name": "Wayne"},
    {"location": "Westchester - except", "rate": 8.375, "code": "5581", "is_city": False, "clean_name": "Westchester"},
    {"location": "Mount Vernon (city)", "rate": 8.375, "code": "5521", "is_city": True, "clean_name": "Mount Vernon"},
    {"location": "New Rochelle (city)", "rate": 8.375, "code": "6861", "is_city": True, "clean_name": "New Rochelle"},
    {"location": "White Plains (city)", "rate": 8.375, "code": "6513", "is_city": True, "clean_name": "White Plains"},
    {"location": "Yonkers (city)", "rate": 8.875, "code": "6511", "is_city": True, "clean_name": "Yonkers"},
    {"location": "Wyoming", "rate": 8.0, "code": "5621", "is_city": False, "clean_name": "Wyoming"},
    {"location": "Yates", "rate": 8.0, "code": "5721", "is_city": False, "clean_name": "Yates"}
]