"""add total_amount

Revision ID: 3710cef6664a
Revises: 4e48171ef203
Create Date: 2026-02-28 22:53:46.643482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3710cef6664a'
down_revision: Union[str, Sequence[str], None] = '4e48171ef203'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taxes', sa.Column('total_amount', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taxes', 'total_amount')
    # ### end Alembic commands ###
