"""setup_order_tax_relation

Revision ID: 8b7145f156f6
Revises: 9187dc963fa7
Create Date: 2026-02-28 09:49:30.014495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8b7145f156f6'
down_revision: Union[str, Sequence[str], None] = '9187dc963fa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'tax')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('tax', mysql.FLOAT(), nullable=False))
    # ### end Alembic commands ###
