"""add null

Revision ID: e08af4033fd3
Revises: 8b7145f156f6
Create Date: 2026-02-28 10:14:09.013084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e08af4033fd3'
down_revision: Union[str, Sequence[str], None] = '8b7145f156f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('taxes', 'jurisdictions',
               existing_type=mysql.VARCHAR(length=5),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('taxes', 'jurisdictions',
               existing_type=mysql.VARCHAR(length=5),
               nullable=False)
    # ### end Alembic commands ###
