"""add city_rate

Revision ID: ff0558843a5f
Revises: e08af4033fd3
Create Date: 2026-02-28 10:42:07.945563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff0558843a5f'
down_revision: Union[str, Sequence[str], None] = 'e08af4033fd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taxes', sa.Column('city_rate', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taxes', 'city_rate')
    # ### end Alembic commands ###
